export const MOVEMENT_INTERACTION_KIND_MINE_ENTER = 'MINE_ENTER';
export const MOVEMENT_INTERACTION_KIND_MONSTER_COMBAT = 'MONSTER_COMBAT';
export const MOVEMENT_INTERACTION_KIND_RESOURCE_COLLECT = 'RESOURCE_COLLECT';
export const MOVEMENT_INTERACTION_KIND_TOWN_VISIT = 'TOWN_VISIT';

export const INTERACTION_OUTCOME_KIND_MINE_ENTERED = 'MINE_ENTERED';
export const INTERACTION_OUTCOME_KIND_MONSTER_DEFEATED = 'MONSTER_DEFEATED';
export const INTERACTION_OUTCOME_KIND_RESOURCE_COLLECTED = 'RESOURCE_COLLECTED';
export const INTERACTION_OUTCOME_KIND_TOWN_VISITED = 'TOWN_VISITED';
